# Generated by Django 5.2.6 on 2026-03-18 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("monthly_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = overall budget (no specific category)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "category__name"],
                "unique_together": {("user", "category", "month", "year")},
            },
        ),
    ]
